version: '3.8'

services:

  # PostgreSQL para DEV
  pg-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: ['dev']

  # PostgreSQL para PROD
  pg-prod:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=produccion
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=contraseña
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: ['prod']

  pgadmin:
    image: dpage/pgadmin4
    container_name: test-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles: ['dev']

volumes:
  pgdata:
  pgadmin-data:
