// Generated by https://quicktype.io

export interface AddProducto {
    id:           string;
    imagen:       string;
    name:         string;
    precio:       number;
    disponible:   boolean;
    ingredientes: null;
    comercio:     null;
}
