// Generated by https://quicktype.io

export interface ListadoUsarios {
    id:                    string;
    email:                 string;
    username:              string;
    password:              string;
    name:                  string;
    lastName:              string;
    phoneNumber:           null | string;
    birthDate:             null;
    fotoUrl:               null | string;
    accountNonExpired:     boolean;
    accountNonLocked:      boolean;
    credentialsNonExpired: boolean;
    enabled:               boolean;
    roles:                 string[];
    createdAt:             null | string;
    lastPasswordChangeAt:  null | string;
    usuarios:              any[];
    inChargeof:            any[];
    favoritos:             any[];
    authorities:           Authority[];
}

export interface Authority {
    authority: string;
}
