// Generated by https://quicktype.io

export interface LoginResponse {
    id:       string;
    fullname: string;
    username: string;
    email:    string;
    fotoUrl:  string;
    token:    string;
}
